/**
 * Sample React Native App
 *
 * adapted from App.js generated by the following command:
 *
 * react-native init example
 *
 * https://github.com/facebook/react-native
 */

import React, { Component } from 'react';
import { Platform, StyleSheet, Text, View } from 'react-native';
import CoreMotionModule from 'react-native-core-motion';

export default class App extends Component<{}> {
  state = {
    status: 'starting',
    message: '--',
    sample: '{}'
  };
  componentDidMount() {
    CoreMotionModule.isAvailable((available) => {
      if (available) {
        CoreMotionModule.recordMotions()
        CoreMotionModule.loadRecordedData()
          .then((resolve) => this.setState({ status: "OK", message: "Count: " + resolve.length, sample: JSON.stringify(resolve[0]) }))
          .catch((error) => this.setState({ status: error.message }));
      }
    })
  }
  render() {
    return (
      <View style={styles.container}>
        <Text style={styles.welcome}>☆CoreMotion example☆</Text>
        <Text style={styles.instructions}>STATUS: {this.state.status}</Text>
        <Text style={styles.welcome}>☆NATIVE CALLBACK MESSAGE☆</Text>
        <Text style={styles.instructions}>{this.state.message}</Text>
        <Text style={styles.welcome}>☆SAMPLE☆</Text>
        <Text style={styles.instructions}>{this.state.sample}</Text>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },
  welcome: {
    fontSize: 20,
    textAlign: 'center',
    margin: 10,
  },
  instructions: {
    textAlign: 'center',
    color: '#333333',
    marginBottom: 5,
  },
});
